#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fail
set -o errexit

NEXTCLOUD_VERSION="22.2.0"
DESTDIR="/var/www/htdocs/nextcloud"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
	redis_connected_clients
	redis_per_sec
	redis_used_memory
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Install nextcloud"
mkdir -p "${DESTDIR}/releases"
cd "${DESTDIR}/releases"
curl -s -L -O https://download.qutic.com/src/nextcloud/nextcloud-$NEXTCLOUD_VERSION.tar.bz2
tar xf nextcloud-$NEXTCLOUD_VERSION.tar.bz2
rm nextcloud-$NEXTCLOUD_VERSION.tar.bz2
mv nextcloud nc-$NEXTCLOUD_VERSION
rm -rf nc-$NEXTCLOUD_VERSION/config

echo "* Setup nextcloud-apps"
NEXTCLOUD_APPS="
	analytics-3.6.1.tar.gz
	apporder.tar.gz
	bookmarks-10.0.2.tar.gz
	calendar.tar.gz
	camerarawpreviews_nextcloud.tar.gz
	checksum.tar.gz
	cms_pico-v1.0.16.tar.gz
	contacts.tar.gz
	cospend-1.4.1.tar.gz
  dashboardcharts.0.1.3.tar.gz
	deck.tar.gz
	dicomviewer.tar.gz
	emlviewer-0.0.23.tar.gz
	epubreader-1.4.6.tar.gz
	event_update_notification-1.3.0.tar.gz
	files_accesscontrol-1.12.1.tar.gz
	files_automatedtagging-1.12.0.tar.gz
	files_linkeditor.tar.gz
	files_markdown.tar.gz
	files_mindmap-0.0.25.tar.gz
	forms.tar.gz
	gpxpod-4.2.8.tar.gz
  gpxedit-0.0.14.tar.gz
	groupfolders.tar.gz
	groupquota.tar.gz
	keeweb-0.6.6.tar.gz
	mail.tar.gz
	maps-0.1.9.tar.gz
	news.tar.gz
	notes.tar.gz
	onlyoffice.tar.gz
	phonetrack-0.6.9.tar.gz
	polls.tar.gz
	quota_warning-1.11.0.tar.gz
	side_menu_v1.28.0.tar.gz
	spreed-12.1.2.tar.gz
	tasks.tar.gz
	telephoneprovider.tar.gz
	timetracker-0.0.72.tar.gz
	video_converter.tar.gz
"

cd nc-${NEXTCLOUD_VERSION}/apps
for nc_app in ${NEXTCLOUD_APPS[@]}; do
  /opt/local/bin/curl -s -L -O "https://download.qutic.com/src/nextcloud/apps-$NEXTCLOUD_VERSION/${nc_app}"
  if [[ -f "${nc_app}" ]]; then
    echo "** Installing app: ${nc_app}"
    /usr/bin/gtar xf "${nc_app}" && rm "${nc_app}" || true
  fi
done

echo "* Setup nextcloud"
cd $DESTDIR
ln -nfs $DESTDIR/releases/nc-$NEXTCLOUD_VERSION current
chown -R www:www "$DESTDIR"

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir -p /var/log/httpd/old
mkdir -p /opt/local/etc/httpd/ssl || true
chmod 0640 /opt/local/etc/httpd/ssl
ln -nfs /opt/local/etc/httpd/ssl /opt/local/etc/httpd/tls

echo "* Add commands to bash-history";
cat >> /root/.bash_history << EOF
sudo -u www php /var/www/htdocs/nextcloud/current/occ upgrade
sudo -u www php /var/www/htdocs/nextcloud/current/occ maintenance:mode --off
sudo -u www php /var/www/htdocs/nextcloud/current/occ config:system:set appstoreenabled --type boolean --value false
sudo -u www php /var/www/htdocs/nextcloud/current/occ db:add-missing-indices
sudo -u www php /var/www/htdocs/nextcloud/current/occ db:add-missing-columns
su - www
tail -f /var/log/php-fpm.log
tail -f /var/log/nginx/access.log
svcadm restart php-fpm ; svcadm restart nginx
svcadm restart php-fpm
svcadm restart nginx
svcs -vx
EOF

# echo "* Enable ipfilter"
# svcadm enable svc:/network/ipfilter:default

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
