#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

NEXTCLOUD_VERSION="14.0.3"
DESTDIR="/var/www/htdocs/nextcloud"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
	redis_connected_clients
	redis_per_sec
	redis_used_memory
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup nextcloud"
NEXTCLOUD_APPS="
	calendar.tar.gz
	contacts.tar.gz
	tasks.tar.gz
	deck.tar.gz
	news.tar.gz
	polls.tar.gz
	flowupload.tar.gz
	bookmarks-0.13.1.tar.gz
	mail.tar.gz
	spreed-4.0.0.tar.gz
	files_markdown.tar.gz
	apporder.tar.gz
	quota_warning-1.3.0.tar.gz
	checksum.tar.gz
	keeweb-0.4.0.tar.gz
"
/opt/qutic/bin/setup-nextcloud

cd $DESTDIR
ln -nfs $DESTDIR/releases/nc-$NEXTCLOUD_VERSION current

chown -R www:www "$DESTDIR"

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Activate redis"
gsed -i \
     -e "s/# maxmemory <bytes>/maxmemory 256mb/" \
     -e "s/# maxmemory-policy noeviction/# maxmemory-policy allkeys-lfu/" \
     -e "s/# unixsocket \/tmp\/redis.sock/unixsocket \/var\/tmp\/redis.sock/" \
     /opt/local/etc/redis.conf

svcadm enable redis

# echo "* Enable ipfilter"
# svcadm enable svc:/network/ipfilter:default

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
