#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fail
set -o errexit

NEXTCLOUD_VERSION="25.0.5"
DESTDIR="/var/www/htdocs/nextcloud"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Install nextcloud"
mkdir -p "${DESTDIR}/releases"
cd "${DESTDIR}/releases"
curl -s -L -O https://download.qutic.com/src/nextcloud/nextcloud-$NEXTCLOUD_VERSION.tar.bz2
tar xf nextcloud-$NEXTCLOUD_VERSION.tar.bz2
rm nextcloud-$NEXTCLOUD_VERSION.tar.bz2
mv nextcloud nc-$NEXTCLOUD_VERSION
rm -rf nc-$NEXTCLOUD_VERSION/config

echo "* Setup nextcloud-apps"
NEXTCLOUD_APPS="
  analytics-4.8.0.tar.gz
  appointments.tar.gz
  apporder.tar.gz
  bbb-v2.4.0.tar.gz
  bookmarks-12.1.0.tar.gz
  calendar-v4.3.2.tar.gz
  camerarawpreviews_nextcloud.tar.gz
  checksum.tar.gz
  cms_pico-v1.0.21.tar.gz
  collectives-2.4.0.tar.gz
  contacts-v5.2.0.tar.gz
  cospend-1.5.8.tar.gz
  deck-v1.8.3.tar.gz
  dicomviewer-1.2.4.tar.gz
  emlviewer-1.0.7.tar.gz
  event_update_notification-v2.1.0.tar.gz
  files_accesscontrol-v1.15.1.tar.gz
  files_automatedtagging-v1.15.3.tar.gz
  files_linkeditor.tar.gz
  files_markdown.tar.gz
  files_mindmap-0.0.27.tar.gz
  files_reader-1.5.3.tar.gz
  forms.tar.gz
  gpxedit-0.0.14.tar.gz
  gpxpod-5.0.9.tar.gz
  groupfolders-v13.1.1.tar.gz
  groupquota-v0.1.10.tar.gz
  keeweb-0.6.12.tar.gz
  libresign-v6.3.0.tar.gz
  mail-v2.2.5.tar.gz
  maps-1.0.2.tar.gz
  news.tar.gz
  notes.tar.gz
  oidc-0.4.7.tar.gz
  onlyoffice.tar.gz
  phonetrack-0.7.4.tar.gz
  polls.tar.gz
  previewgenerator-v5.2.2.tar.gz
  quota_warning-v1.16.0.tar.gz
  side_menu_v3.7.2.tar.gz
  sip_trip_phone.tar.gz
  spreed-v15.0.5.tar.gz
  timetracker-0.0.79.tar.gz
  video_converter.tar.gz
"

cd nc-${NEXTCLOUD_VERSION}/apps
for nc_app in ${NEXTCLOUD_APPS[@]}; do
  /opt/local/bin/curl -s -L -O "https://download.qutic.com/src/nextcloud/apps-$NEXTCLOUD_VERSION/${nc_app}"
  if [[ -f "${nc_app}" ]]; then
    echo "** Installing app: ${nc_app}"
    /usr/bin/gtar xf "${nc_app}" && rm "${nc_app}" || true
  fi
done

echo "* Setup nextcloud"
cd $DESTDIR
ln -nfs $DESTDIR/releases/nc-$NEXTCLOUD_VERSION current
chown -R www:www "$DESTDIR"

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir -p /var/log/httpd/old
mkdir -p /opt/local/etc/httpd/ssl || true
chmod 0640 /opt/local/etc/httpd/ssl
ln -nfs /opt/local/etc/httpd/ssl /opt/local/etc/httpd/tls

echo "* Add commands to bash-history";
cat >> /root/.bash_history << EOF
sudo -u www php /var/www/htdocs/nextcloud/current/occ upgrade
sudo -u www php /var/www/htdocs/nextcloud/current/occ maintenance:mode --off
sudo -u www php /var/www/htdocs/nextcloud/current/occ config:system:set appstoreenabled --type boolean --value false
sudo -u www php /var/www/htdocs/nextcloud/current/occ db:add-missing-indices
sudo -u www php /var/www/htdocs/nextcloud/current/occ db:add-missing-columns
su - www
tail -f /var/log/php-fpm.log
tail -f /var/log/nginx/access.log
svcadm restart php-fpm ; svcadm restart nginx
svcadm restart php-fpm
svcadm restart nginx
svcs -vx
EOF
chmod 0600 /root/.bash_history

# echo "* Enable ipfilter"
# svcadm enable svc:/network/ipfilter:default

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
